---
- name: Abre puerto 25
  hosts: all
   
  tasks:    
    - name: Configura Firewall Windows 
      win_firewall_rule:
        name: Ansible SMTP
        enable: no
        state: absent
        localport: 25
        action: allow
        direction: In
        protocol: TCP        
