---

- name: Habilita IIS y deploya sitio web
  hosts: all
  gather_facts: false
  tasks:
    - name: Instala IIS
      win_feature:
        name: "Web-Server"
        state: absent
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
              
    #- name: Deploya Web desde GitHub
     # win_get_url:
      #  url: 'https://raw.githubusercontent.com/elgustavoreyes/ansible-examples/master/windows/index.html'
       # dest: 'C:\inetpub\wwwroot\ansible.html'
        
    - name: Reinicia Server
      win_reboot:
