---
- name: Desinstala Apache HTTP 
  hosts: all
   
  tasks:    
    - name: Desinstala Apache Webserver
      win_package: 
        path: 'C:\Users\Administrator\Downloads\httpd-2.2.25-win32-x86-no_ssl.msi'
        state: absent
        product_id: '{85262A06-2D8C-4BC1-B6ED-5A705D09CFFC}'
    - name: Elimina archivo instalación
      win_file:
        path: 'C:\Users\Administrator\Downloads\httpd-2.2.25-win32-x86-no_ssl.msi'
        state: absent
    - name: Reinicia Sistema
      win_reboot:
        msg: 'Reiniciando equipo...Iniciado por Ansible'
